project/auth.py
#from os import access
from flask import Blueprint, render_template, \
    redirect, url_for, request, flash, session
from flask_mail import Message
from . import db, mail
from .models import users
from flask_login import login_user, logout_user, \
    login_required, current_user
from werkzeug.security import generate_password_hash, \
    check_password_hash
from datetime import timedelta


auth = Blueprint("auth", __name__)

# When you want to have blueprint-specific 
# templates and static files:

#auth = Blueprint(
# "auth", __name__, 
# template_folder='templates',
# static_folder='static'
# )



#--------------------------------------------------------------------
#--------------------------------------------------------------------



@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        user = users.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Successfully logged in!', category='success')
                login_user(user, remember=False)
                # Documentation on login_user:
                # https://stackoverflow.com/questions/27965897/why-does-setting-remember-false-still-keep-me-logged-in
                session.permanent = True
                return redirect(url_for('views.index'))
            else:
                flash('Password is incorrect. Please try again.', 
                    category='error')
        else:
            flash('That username does not exist. Please try again or contact \
                your system administrator.', 
                category='error')

    flash('Please log in to continue.', category='error')       

    return render_template('login.html', user=current_user)


#--------------------------------------------------------------------
#--------------------------------------------------------------------



@auth.route("/signup", methods=['GET', 'POST'])
def signup():

    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username_signup")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists = users.query.filter_by(email=email).first()
        username_exists = users.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use. \
            Choose another email.', category='error')
        elif username_exists:
            flash('Username is already in use. \
            Choose another username.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        else:
            flash("Thanks for signing up! We'll get back to you \
                via email once we create your account.", 
                category='success')
            
            # Signup email code:
            msg = Message('New User Signup', 
                sender = 'hello@carbonfree.dev', 
                recipients = ['bharding@carbonfree.cc'])
            msg.html = render_template('email.html', email=email,
                username=username, password=password1)
            mail.send(msg)  
            
            
            # Redirect the logged in user to 'index.html':
            return redirect(url_for('views.index'))


    return render_template('signup.html', user=current_user)



#--------------------------------------------------------------------
#--------------------------------------------------------------------



@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash('You have been logged out!', category='success')

    return redirect(url_for('auth.login'))



#--------------------------------------------------------------------
#--------------------------------------------------------------------

project/views.py
from flask import Blueprint, render_template, request, redirect, flash, session
from flask_login import login_required, current_user
from sqlalchemy import func, or_, and_
from .models import carriers_db, appts_db, log_db, carriers_db
from . import db, mail
from flask_mail import Message
import datetime

views = Blueprint("views", __name__)

# When you want to have blueprint-specific 
# templates and static files:

#views = Blueprint(
# "views", __name__, 
# template_folder='templates',
# static_folder='static'
# )

#--------------------------------------------------------------------
#--------------------------------------------------------------------


@views.route('/')
@login_required
def index():

    search_material = request.args.getlist('material_filter')
    
    if request.args.get('start_date_filter') is None:
        start_date = datetime.datetime.now().strftime("%Y-%m-%d")
    else:
        start_date = request.args.get('start_date_filter')

    if request.args.get('end_date_filter') is None:
        end_date = datetime.datetime.now().strftime("%Y-%m-%d")
    else:
        end_date = request.args.get('end_date_filter')

    if request.args.get('start_time_filter') is None:
        start_time = '00:00'
    else:
        start_time = request.args.get('start_time_filter')

    if request.args.get('end_time_filter') is None:
        end_time = '23:59'
    else:
        end_time = request.args.get('end_time_filter')

    # Subquery to match the status requested. 
    status_selection = request.args.get('status')
    if status_selection == 'All':
        status_query = db.session.query(appts_db.id).subquery()
    else:
        status_query = db.session.query(appts_db.id) \
            .filter(appts_db.status == status_selection).subquery()
        
    # Subquery to match the carrier requested.
    carrier_selection = request.args.get('carrier')
    if carrier_selection == 'All':
        carrier_query = db.session.query(appts_db.id).subquery()
    else:
        carrier_query = db.session.query(appts_db.id) \
            .filter(appts_db.carrier == carrier_selection).subquery()

    appts = db.session.query(appts_db) \
        .filter(appts_db.id.in_(status_query)) \
        .filter(appts_db.id.in_(carrier_query)) \
        .filter(appts_db.material.in_(search_material)) \
        .filter(appts_db.pickup_date.between(start_date, end_date)) \
        .filter(appts_db.pickup_time.between(start_time, end_time)) \
        .order_by(appts_db.pickup_date, appts_db.pickup_time).all()     

  
    # To generate the carriers within the dropdown list
    carriers = carriers_db.query.order_by(carriers_db.carrier_name).all()

    ############################################################################
    # Sum the queried volumes by product.
    # And count the number of trucks.
    hcl_volumeList = []
    hcl_load_counter = 0
    for appt in appts:
        if appt.material == '36% HCl' or \
        appt.material == '32% HCl' or \
        appt.material == '15% HCl':
            hcl_volumeList.append(appt.volume)
            hcl_load_counter = hcl_load_counter + 1
    hcl_gallons = (sum(hcl_volumeList))/1000
    hcl_load_total_count = hcl_load_counter

    caustic_volumeList = []
    caustic_load_counter = 0
    for appt in appts:
        if appt.material == '50% Caustic' or \
        appt.material == '32% Caustic' or \
        appt.material == '30% Caustic' or \
        appt.material == '25% Caustic' or \
        appt.material == '20% Caustic':
            caustic_volumeList.append(appt.volume)
            caustic_load_counter = caustic_load_counter + 1
    caustic_gallons = (sum(caustic_volumeList))/1000
    caustic_load_total_count = caustic_load_counter

    bleach_volumeList = []
    bleach_load_counter = 0
    for appt in appts:
        if appt.material == '12.5% Bleach' or \
        appt.material == '10% Bleach' or \
        appt.material == '14%+ Bleach':
            bleach_volumeList.append(appt.volume)
            bleach_load_counter = bleach_load_counter + 1
    bleach_gallons = (sum(bleach_volumeList))/1000
    bleach_load_total_count = bleach_load_counter

    ############################################################################


    return render_template(
        'index.html', 
        appts=appts, 
        carriers=carriers, 
        carrier_selection=carrier_selection,
        status_selection=status_selection,
        user=current_user,
        hcl_gallons=hcl_gallons,
        hcl_load_total_count=hcl_load_total_count,
        caustic_gallons=caustic_gallons,
        caustic_load_total_count=caustic_load_total_count,
        bleach_gallons=bleach_gallons,
        bleach_load_total_count=bleach_load_total_count,
        start_date=start_date,
        end_date=end_date,
        search_material=search_material,
        start_time=start_time,
        end_time=end_time
    )


#--------------------------------------------------------------------
#--------------------------------------------------------------------


@views.route('/history', methods=['GET'])
@login_required
def history():
    if request.args.get('number_of_records') is None:
        query_limit = "10"
    else:
        query_limit = request.args.get('number_of_records')

    if request.args.get('action') is None:
        action_choice = 'Created'
    else:
        action_choice = request.args.get('action')

    log_list = db.session.query(log_db) \
        .filter(log_db.action == action_choice) \
        .order_by(log_db.id.desc()) \
        .limit(query_limit).all()

    return render_template(
        'history.html', 
        query_limit=query_limit, 
        user=current_user,
        action_choice=action_choice,
        log_list=log_list
    )


#--------------------------------------------------------------------
#--------------------------------------------------------------------


@views.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        carrier_name = request.form['carrier']
        requested_volume = request.form['volume']
        material_name = request.form['material']
        pickup_date_input = request.form['pickup_date']
        pickup_time_input = request.form['pickup_time']
        PO_number = request.form['PO_number']
        status = 'Scheduled'
        notes = request.form['notes']


        if 'HCl' in material_name:
            category = 'HCl'
        if 'Caustic' in material_name:
            category = 'Caustic'
        if 'Bleach' in material_name:
            category = 'Bleach'


        # Try to find an appointment in that time slot.
        duplicate_appt = appts_db.query.filter(and_(
            appts_db.material.contains(category),
            appts_db.pickup_date == pickup_date_input,
            appts_db.pickup_time == pickup_time_input
            )).first()
        
        if duplicate_appt is None:

            new_appt = appts_db(
                carrier=carrier_name, 
                volume=requested_volume,
                material=material_name, 
                pickup_date=pickup_date_input, 
                pickup_time=pickup_time_input, 
                PO_number=PO_number,
                status=status,
                notes=notes
            )

            create_new_log = log_db(
                action="Created",
                carrier=carrier_name, 
                volume=requested_volume,
                material=material_name, 
                pickup_date=pickup_date_input, 
                pickup_time=pickup_time_input, 
                PO_number=PO_number,
                modified_by=current_user.username
            )


            db.session.add_all([new_appt, create_new_log])
            db.session.commit()
            flash('Your appointment was successfully created!', category='success')
            return redirect('/')
        
        
        else:
            flash('This time slot is already taken. Please check the schedule and try again.', category='error')
            carriers = carriers_db.query.order_by(carriers_db.carrier_name).all()
            return render_template('create.html', carriers=carriers, user=current_user)
    
        

    else:
        carriers = carriers_db.query.order_by(carriers_db.carrier_name).all()
        # 'carriers' is passed to the 'create.html' page where it is rendered. 
        return render_template('create.html', carriers=carriers, user=current_user)


#--------------------------------------------------------------------
#--------------------------------------------------------------------


@views.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update(id):
    appt = appts_db.query.get_or_404(id)

    if request.method == 'POST' :

        # If the user is just marking the appt as "Completed",
        # then just update the appt list and NOT the History log.
        # This is done to limit the number of nuisance entries 
        # made to the history log. 
        if request.form['status'] == "Completed":

            appt.carrier = request.form['carrier']
            appt.volume = request.form['volume_update']
            appt.material = request.form['material_update']
            appt.pickup_date = request.form['pickup_date']
            appt.pickup_time = request.form['pickup_time']
            appt.PO_number = request.form['PO_number_update']
            appt.status = request.form['status']
            appt.notes = request.form['notes']

            db.session.commit()
            flash('Appointment was successfully marked as "completed".', category='success')
            return redirect('/')
    
        # Else, if user is doing a normal update, then update
        # the appt list AND add the change to the History log:
        else:
            # Record the ORIGINAL appt data before the update:
            update_new_log_old = log_db(
                action="Updated - Old",
                carrier=appt.carrier,

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge">-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" 
    crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='/favicon.ico') }}">
    <script src="{{ url_for('static', filename='js/my-index.js') }}"></script>

    <title>CF Logistics</title>
    {% block head %}
    {% endblock %}
</head>

<body>
    <ul>
        {% if user.is_authenticated and user.access_ranking == 3 %}
        <li><a href="{{ url_for('views.index') }}">Home</a></li>
        <li><a href="{{ url_for('views.create') }}">Create</a></li>
        <li><a href="{{ url_for('views.history') }}">History</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% elif user.is_authenticated %}
        <li><a href="{{ url_for('views.index') }}">Home</a></li>
        <li><a href="{{ url_for('views.history') }}">History</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
        <li><a href="{{ url_for('auth.signup') }}">Signup</a></li>
        {% endif %}
    </ul>

    <img id="logo"
        src="/static/carbonfree logo.png" 
        width: 300px;
        height: 200px;
        style="width: 300px; height:80px; object-fit: cover;">

    <h1>CarbonFree Logistics Management System</h1>

    {% if user.is_authenticated %}
    <p class="logged-in-as">Logged in as: <b>{{ user.username }}</b></p>
    {% endif %}


        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'success' %}
                        <div class="alert alert-success mx-5" role="alert">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-danger mx-5" role="alert">
                            {{ message }}                            
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}


<br>

    {% block body %}
    {% endblock %}
</body>

</html>

project/templates/create.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
    
{% block body %}
<h2>Create a New Appointment</h2><br>

<div class="container mb-5">
    <form action="{{ url_for('views.create') }}" 
        method="POST" 
        onsubmit="return validateForm()" 
        id="new_appt_form"
        name="create_appt_form">
        


        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-4">
                <label for="PO_number"><b>PO Number:</b></label>
                <input type="text" id="PO_number" name="PO_number" 
                    placeholder="PO-xxxxx" class="form-control">
            </div>
        </div><br>



        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-4">
                <!--This Jinja for loop goes through each carrier 
                in the 'carriers' column that is passed from the view 
                function and adds all the unique values to the
                dropdown list.-->
                <label><b>Choose a Customer:</b></label><br>
                <select name="carrier" class="form-select">
                    <option disabled selected value></option>
                    {% for carrier in carriers %}
                    <option value = "{{ carrier.carrier_name }}">{{ carrier.carrier_name }}</option>
                    {% endfor %}
                </select>
                
                <p class="note">Don't see your customer in the dropdown menu?</p>
                <a
                    href="{{ url_for('views.new_carrier') }}"
                    class="btn btn-outline-success"
                    role="button">Create New Customer
                </a>
            </div>
        </div><br>





        <div class="row">
            <p><b>Select a product:</b></p>

            <div class="col-sm-4 col-md-3 col-lg-2">

                <p>HCl:</p>
                <div class="form-check">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="material" 
                        id="36% HCl" 
                        value="36% HCl">
                    <label 
                        class="form-check-label"
                        for="36% HCl">36% HCl</label>
                </div>

                <div class="form-check">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="material" 
                        id="32% HCl" 
                        value="32% HCl">
                    <label 
                        class="form-check-label"
                        for="32% HCl">32% HCl</label>
                </div>                        

                <div class="form-check">
                    <input 
                        class="form-check-input" 
                        type="radio" 
                        name="material" 
                        id="15% HCl" 
                        value="15% HCl">
                    <label 
                        class="form-check-label"
                        for="15% HCl">15% HCl</label>
                </div>

            </div>

            <div class="col-sm-4 col-md-3 col-lg-2">

                <p>Caustic:</p>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="50% Caustic" value="50% Caustic">
                    <label for="50% Caustic">50% Caustic</label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="32% Caustic" value="32% Caustic">
                    <label for="32% Caustic">32% Caustic</label>
                </div>

                <div class="form-check">  
                    <input class="form-check-input" type="radio" name="material" id="30% Caustic" value="30% Caustic">
                    <label for="30% Caustic">30% Caustic</label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="25% Caustic" value="25% Caustic">
                    <label for="25% Caustic">25% Caustic</label>
                </div>

                <div class="form-check">  
                    <input class="form-check-input" type="radio" name="material" id="20% Caustic" value="20% Caustic">
                    <label for="20% Caustic">20% Caustic</label>
                </div>

            </div>

            <div class="col-sm-4 col-md-3 col-lg-2">

                <p>Bleach:</p>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="14%+ Bleach" value="14%+ Bleach">
                    <label for="14%+ Bleach">14%+ Bleach</label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="12.5% Bleach" value="12.5% Bleach">
                    <label for="12.5% Bleach">12.5% Bleach</label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" name="material" id="10% Bleach" value="10% Bleach">
                    <label for="10% Bleach">10% Bleach</label>
                </div>

            </div>

        </div><br>




        <div class="row">
            <div class="col-8 col-sm-6 col-md-6 col-lg-4">
                <label for="pickup_date"><b>Pickup Date:</b></label>
                <input type="date" id="pickup_date" name="pickup_date" class="form-control">
            </div>
        </div><br>



        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-4">
                <label for="pickup_time"><b>Pickup Time:</b></label>
                <input type="time" id="pickup_time" name="pickup_time" class="form-control">
            </div>
        </div><br>





        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-4">
                <label for="volume"><b>Requested Volume [gallons]:</b></label><br>
                <input class="form-control" 
                    type="number" 
                    name="volume" 
                    id="volume" 
                    value="volume">
            </div>
        </div><br>


        <div class="row">
            <div class="col-6 col-sm-6 col-md-6 col-lg-4">
                <label for="notes"><b>Notes:</b></label><br>
                <input class="form-control" 
                    type="text" 
                    name="notes" 
                    id="notes">
            </div>
        </div><br><br>


        <button
            type="submit"  
            form="new_appt_form"
            value="Submit" 
            class="btn btn-outline-success">Submit</button>
        </button> 

    </form>

</div>






<script>
    function validateForm() {
        let w = document.forms["create_appt_form"]["carrier"].value;
            x = document.forms["create_appt_form"]["pickup_date"].value;
            y = document.forms["create_appt_form"]["pickup_time"].value;
            z = document.forms["create_appt_form"]["material"].value;

        if (w == "") {
            alert("Customer field cannot be left blank");
            return false;   

        } else if (x == "") {
            alert("Date field cannot be left blank");
            return false;

        } else if (y == "") {
            alert("Time field cannot be left blank");
            return false;

        } else if (z == "") {
            alert("Please choose a product");
            return false;

        }


    }
</script>




{% endblock %}

project/templates/email.html
<p>New User Request</p>

<li>User's email: {{ email }}</li>
<li>Requested Username: {{ username }}</li>
<li>Requested Password: {{ password }}</li>

<p>Best,</p>
<p>CarbonFree Admin</p>

project/templates/history.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
    
{% block body %}

<div class="container ml-5">
    <form class="form">

        <div class="row pb-3">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <label for="log_query">Number of records to view:</label>
                <select name="number_of_records" id="log_query" class="form-select-sm">
                    <option value="10" 
                    {% if query_limit == "10" %} selected {% endif %}>10</option>
                    <option value="25" 
                    {% if query_limit == "25" %} selected {% endif %}>25</option>
                    <option value="50" 
                    {% if query_limit == "50" %} selected {% endif %}>50</option>
                    <option value="100" 
                    {% if query_limit == "100" %} selected {% endif %}>100</option>
                </select>
            </div>
        </div>


        <div class="row pb-3">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <label for="action">Action:</label>
                <select name="action" id="action" class="form-select-sm">

                    <option value="Created" 
                    {% if action_choice == "Created" %} selected {% endif %}>Created</option>

                    <option value="Updated" 
                    {% if action_choice == "Updated" %} selected {% endif %}>Updated</option>

                    <option value="Deleted" 
                    {% if action_choice == "Deleted" %} selected {% endif %}>Deleted</option>

                </select>


            </div>
        </div>


        <div class="row">
            <div class="col-6 col-sm-6 col-md-4 col-lg-4">
                <input type="submit" value="Search" class="btn btn-outline-success">
            </div>
        </div>


    </form>


</div>




<h2>Appointment Change Log</h2>


<div class="table-responsive mx-5 mb-5">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Action</th>
                <th scope="col">Customer</th>
                <th scope="col">Product</th>
                <th scope="col">Volume [gal]</th>
                <th scope="col">Pickup Date [YYYY-MM-DD]</th>
                <th scope="col">Pickup Time [24-hr]</th>
                <th scope="col">PO #</th>
                <th scope="col">Notes</th>
                <th scope="col">Date Modified</th>
                <th scope="col">Modified By</th>
            </tr>
        </thead>

        <tbody>
            {% for item in log_list %}
                <tr>
                    <td>{{ item.action }}</td>
                    <td>{{ item.carrier }}</td>
                    <td>{{ item.material }}</td>
                    <td>{{ item.volume }}</td>
                    <td>{{ item.pickup_date }}</td>
                    <td>{{ item.pickup_time }}</td>
                    <td>{{ item.PO_number }}</td>
                    <td>{{ item.notes }}</td>
                    <td>{{ item.modified_on.strftime("%Y-%m-%d %H:%M:%S") }}</td>
                    <td>{{ item.modified_by }}</td>
                </tr>
            {% endfor %}
        </tbody>

    </table>

</div>

{% endblock %}

project/templates/login.html
{% extends "base.html" %}

{% block title %}
{% endblock %}

{% block body %}

<div class="container">

    <form method="POST">

        <h3>Login</h3>


        <!--the mb-# refers to the number of breaks after the div-->
        <!--placeholder attribute refers to the text within the input field-->



        <div class="form-floating mb-3">
            <input type="text" id="username" placeholder="Username"
                class="form-control" name="username">
            <label for="username">Username</label>
        </div>

        
        <!--
        <div class="form-floating mb-3">
            <input type="text" id="test" placeholder="test"
                class="form-control" name="test">
            <label for="test">test</label>
        </div>
        -->


        <div class="form-floating mb-3">
            <input type="password" id="password" placeholder="Password"
                class="form-control" name="password">
            <label for="password">Password</label>
        </div>



        <button type="submit" class="btn btn-outline-success">Login</button>


    </form>

</div>


{% endblock %}

project/templates/new_carrier.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
    
{% block body %}
    <h2>Create New Carrier</h2><br>


    <div class="container">

        <form action="/new_carrier" method="POST" class="form" onsubmit="new_carrier_popup()">
        <!--data is sent to the 'new_carrier' route-->

            <div class="row">
                <div class="col-8 col-sm-8 col-md-6 col-lg-4">
                    <label for="carrier_name">Carrier Name</label>
                    <input class="form-control" type="text" name="carrier_name" id="carrier_name" 
                        placeholder="Carrier Name">
                </div>
            </div><br>


            <div class="row">
                <div class="col-8 col-sm-8 col-md-6 col-lg-4">
                    <label for="phone">Phone Number (###-###-####)</label>
                    <input type="tel" id="carrier_phone" name="carrier_phone" 
                        placeholder="210-555-5555" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" 
                        class="form-control">
                </div>
            </div><br>

            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">                            
                    <input type="submit" id="new_carrier_submit" value="Submit" 
                        class="btn btn-outline-success">
                </div>
            </div>

        </form>
    </div>

{% endblock %}

project/templates/signup.html
{% extends "base.html" %}

{% block title %}
{% endblock %}

{% block body %}

<div class="container">

    <form method="POST">

        <h3>Signup</h3>

        <div class="form-floating mb-3">
            <input type="email" id="email" name="email" class="form-control"
                placeholder="Email Address">
            <label for="email">Email Address</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" id="username_signup" name="username_signup" 
                class="form-control" placeholder="Username">
            <label for="username_signup">Username</label>
        </div>

        <div class="form-floating mb-3">
            <input type="password" id="password1" name="password1" 
                class="form-control" placeholder="Password">
            <label for="password1">Password</label>
        </div>

        <div class="form-floating mb-3">
            <input type="password" id="password2" name="password2" 
                class="form-control" placeholder="Re-enter Password">
            <label for="password2">Re-enter Password</label>
        </div>

        <button type="submit" class="btn btn-outline-success">Create Account</button>

    </form>


</div>



{% endblock %}